### PR TITLE
Fix peek Char

### LINKED ISSUE #224: `peek(s::TranscodingStream, ::Type{Char})` errors
Here is a MWE:

```julia-repl
julia> using TranscodingStreams

julia> s=NoopStream(IOBuffer("🐨"))
NoopStream{IOBuffer}(<mode=idle>)

julia> peek(s, Char)
ERROR: ArgumentError: NoopStream{IOBuffer} not marked
Stacktrace:
 [1] reset(stream::NoopStream{IOBuffer})
   @ TranscodingStreams ~/.julia/packages/TranscodingStreams/F7ot4/src/stream.jl:253
 [2] peek(s::NoopStream{IOBuffer}, ::Type{Char})
   @ Base ./io.jl:331
 [3] top-level scope
   @ REPL[13]:1

julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 7800X3D 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
```

The issue is that this package is missing an implementation for `Base.peek(s::TranscodingStream, ::Type{UInt8})::UInt8`

### PR DESCRIPTION
**Pull request by nhz2**
Fixes #224 by implementing `Base.peek(s::TranscodingStream, ::Type{UInt8})::UInt8`

### CODE REVIEW

File: src/stream.jl [hunk 1]
```diff
@@ -314,7 +314,7 @@ end
 # Read Functions
 # --------------
 
-function Base.read(stream::TranscodingStream, ::Type{UInt8})
+function Base.peek(stream::TranscodingStream, ::Type{UInt8})::UInt8
```
Comment (mkitti) [inline src/stream.jl:317]: Could you add a comment here so that someone in the future understands how this is related to `peek(::TranscodingStream, ::Type{Char})` ?

**Review by mkitti — APPROVED** [review]
